import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api } from '../services/api'
import { useAuth } from '../contexts/AuthContext'
import type { Appointment, Patient, Professional } from '../types'
import '../patients.css'
import '../agenda.css'

const today = new Date().toISOString().slice(0, 10)
const labels: Record<string, string> = { AGENDADO: 'Agendado', CONFIRMADO: 'Confirmado', REALIZADO: 'Realizado', FALTOU: 'Faltou', CANCELADO: 'Cancelado' }

export function AgendaPage() {
  const { user } = useAuth(); const [items, setItems] = useState<Appointment[]>([]); const [patients, setPatients] = useState<Patient[]>([]); const [professionals, setProfessionals] = useState<Professional[]>([]); const [date, setDate] = useState(today); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const patientNames = useMemo(() => new Map(patients.map((patient) => [patient.id, patient.name])), [patients]); const professionalNames = useMemo(() => new Map(professionals.map((professional) => [professional.id, professional.name])), [professionals])
  const load = (currentDate = date) => api<Appointment[]>(`/api/appointments?date_from=${currentDate}&date_to=${currentDate}`).then(setItems).catch((e: Error) => setError(e.message))
  useEffect(() => { load(); api<Patient[]>('/api/patients').then(setPatients).catch((e: Error) => setError(e.message)); api<Professional[]>('/api/professionals').then(setProfessionals).catch((e: Error) => setError(e.message)) }, [])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const professionalId = user?.role === 'PROFISSIONAL' ? user.professional_id : Number(form.get('professional_id')); if (!professionalId) { setError('Selecione um profissional.'); return } setSaving(true); setError(''); try { await api('/api/appointments', { method: 'POST', body: JSON.stringify({ patient_id: Number(form.get('patient_id')), professional_id: professionalId, appointment_date: form.get('appointment_date'), start_time: form.get('start_time'), end_time: form.get('end_time'), status: 'AGENDADO', notes: form.get('notes') || null }) }); formElement.reset(); await load(date) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível criar o agendamento.') } finally { setSaving(false) } }
  const updateStatus = async (id: number, status: string) => { try { await api(`/api/appointments/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(date) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível atualizar o atendimento.') } }
  return <><header className="page-heading"><div><h1>Agenda</h1><p>Atendimentos, confirmações e presença.</p></div><input aria-label="Data" type="date" value={date} onChange={(event) => { setDate(event.target.value); load(event.target.value) }} /></header><details className="registration"><summary>Novo agendamento</summary><form className="professional-form" onSubmit={submit}>{user?.role === 'ADMIN' && <select name="professional_id" required defaultValue=""><option value="" disabled>Profissional</option>{professionals.filter((professional) => professional.active).map((professional) => <option value={professional.id} key={professional.id}>{professional.name}</option>)}</select>}<select name="patient_id" required defaultValue=""><option value="" disabled>Paciente</option>{patients.filter((patient) => patient.active).map((patient) => <option value={patient.id} key={patient.id}>{patient.name}</option>)}</select><div className="entry-form"><input name="appointment_date" type="date" defaultValue={date} required /><input name="start_time" type="time" required /><input name="end_time" type="time" required /></div><textarea name="notes" rows={2} placeholder="Observações" /><button disabled={saving}>{saving ? 'Agendando…' : 'Criar agendamento'}</button></form></details>{error && <p className="error">{error}</p>}<section className="agenda">{items.length === 0 ? <p>Nenhum atendimento nesta data.</p> : items.map((item) => <article key={item.id} className={`appointment ${item.status.toLowerCase()}`}><div><strong>{item.start_time.slice(0, 5)} – {item.end_time.slice(0, 5)}</strong><span>{patientNames.get(item.patient_id) ?? `Paciente #${item.patient_id}`}</span>{user?.role === 'ADMIN' && <small>{professionalNames.get(item.professional_id) ?? `Profissional #${item.professional_id}`}</small>}</div><div className="appointment-actions"><small>{labels[item.status] ?? item.status}</small>{!['REALIZADO', 'FALTOU', 'CANCELADO'].includes(item.status) && <><button onClick={() => void updateStatus(item.id, 'CONFIRMADO')}>Confirmar</button><button onClick={() => void updateStatus(item.id, 'REALIZADO')}>Realizado</button><button className="danger-button" onClick={() => void updateStatus(item.id, 'FALTOU')}>Faltou</button><button className="cancel-button" onClick={() => void updateStatus(item.id, 'CANCELADO')}>Cancelar</button></>}</div></article>)}</section></> }
