import { FormEvent, useEffect, useState } from 'react'
import { api } from '../services/api'
import { useAuth } from '../contexts/AuthContext'
import type { MedicalRecord, Patient, Professional } from '../types'
import '../patients.css'
import '../records.css'

export function MedicalRecordsPage() {
  const { user } = useAuth(); const [patients, setPatients] = useState<Patient[]>([]); const [professionals, setProfessionals] = useState<Professional[]>([]); const [records, setRecords] = useState<MedicalRecord[]>([])
  const [patientId, setPatientId] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { api<Patient[]>('/api/patients').then(setPatients).catch((e: Error) => setError(e.message)); if (user?.role === 'ADMIN') api<Professional[]>('/api/professionals').then(setProfessionals).catch((e: Error) => setError(e.message)) }, [user?.role])
  useEffect(() => { if (!patientId) { setRecords([]); return } api<MedicalRecord[]>(`/api/medical-records?patient_id=${patientId}`).then(setRecords).catch((e: Error) => setError(e.message)) }, [patientId])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!patientId) { setError('Selecione um paciente.'); return } const formElement = event.currentTarget; const form = new FormData(formElement); const professionalId = user?.role === 'PROFISSIONAL' ? user.professional_id : Number(form.get('professional_id')); if (!professionalId) { setError('Selecione um profissional.'); return } setSaving(true); setError(''); try { await api('/api/medical-records', { method: 'POST', body: JSON.stringify({ patient_id: Number(patientId), professional_id: professionalId, record_date: form.get('record_date'), category: form.get('category'), content: form.get('content') }) }); formElement.reset(); setRecords(await api<MedicalRecord[]>(`/api/medical-records?patient_id=${patientId}`)) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível criar o prontuário.') } finally { setSaving(false) } }
  return <><header className="page-heading"><div><h1>Prontuários</h1><p>Registros clínicos protegidos por vínculo profissional–paciente.</p></div></header><label className="record-filter">Paciente<select value={patientId} onChange={(event) => setPatientId(event.target.value)}><option value="">Selecione um paciente</option>{patients.map((patient) => <option value={patient.id} key={patient.id}>{patient.name}</option>)}</select></label>{patientId && <><form className="professional-form record-form" onSubmit={submit}>{user?.role === 'ADMIN' && <select name="professional_id" required defaultValue=""><option value="" disabled>Profissional responsável</option>{professionals.map((professional) => <option value={professional.id} key={professional.id}>{professional.name}</option>)}</select>}<input name="record_date" type="date" required /><input name="category" placeholder="Categoria do registro" required /><textarea name="content" rows={5} placeholder="Evolução ou observações clínicas" required /><button disabled={saving}>{saving ? 'Salvando…' : 'Registrar atendimento'}</button></form><section className="records">{records.map((record) => <article key={record.id}><div><strong>{new Date(`${record.record_date}T12:00:00`).toLocaleDateString('pt-BR')}</strong><span>{record.category}</span></div><p>{record.content}</p></article>)}{!records.length && <p>Nenhum registro para este paciente.</p>}</section></>}{error && <p className="error">{error}</p>}</> }
