import { FormEvent, useEffect, useState } from 'react'
import { api } from '../services/api'
import type { Professional } from '../types'

export function ProfessionalsPage() {
  const [items, setItems] = useState<Professional[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [categories, setCategories] = useState<string[]>([])
  const options = ['Fonoaudiologia', 'Psicologia ABA e TCC', 'Psicomotricista', 'Psicopedagogia', 'Terapia Ocupacional', 'Terapia Alimentar', 'Musicoterapia', 'Avaliação Neuropsicológica', 'Orientação Parental']
  const load = () => api<Professional[]>('/api/professionals').then(setItems).catch((e: Error) => setError(e.message))
  useEffect(() => { load() }, [])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!categories.length) { setError('Selecione ao menos uma especialidade.'); return } const form = event.currentTarget; setSaving(true); setError(''); const values = new FormData(form); try { await api('/api/professionals', { method: 'POST', body: JSON.stringify({ name: values.get('name'), email: values.get('email'), phone: values.get('phone') || null, categories, active: true }) }); form.reset(); setCategories([]); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível cadastrar.') } finally { setSaving(false) } }
  const toggle = (option: string) => setCategories((current) => current.includes(option) ? current.filter((item) => item !== option) : [...current, option])
  const setActive = async (id: number, name: string, active: boolean) => { const action = active ? 'reativar' : 'desativar'; const message = active ? `Reativar ${name}?` : `Desativar ${name}? O acesso ao sistema também será bloqueado.`; if (!window.confirm(message)) return; try { if (active) await api(`/api/professionals/${id}/active?active=true`, { method: 'PATCH' }); else await api(`/api/professionals/${id}`, { method: 'DELETE' }); await load() } catch (e) { setError(e instanceof Error ? e.message : `Não foi possível ${action} o profissional.`) } }
  return <><header className="page-heading"><div><h1>Profissionais</h1><p>Equipe e especialidades da clínica.</p></div></header><form className="professional-form" onSubmit={submit}><div className="entry-form"><input name="name" placeholder="Nome" required /><input name="email" type="email" placeholder="E-mail" required /><input name="phone" placeholder="Telefone" /></div><fieldset className="category-picker"><legend>Especialidades</legend><div>{options.map((option) => <button type="button" className={categories.includes(option) ? 'category selected' : 'category'} onClick={() => toggle(option)} key={option} aria-pressed={categories.includes(option)}>{option}</button>)}</div></fieldset><button disabled={saving}>{saving ? 'Salvando…' : 'Cadastrar profissional'}</button></form>{error && <p className="error">{error}</p>}<section className="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Especialidades</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.email}</td><td>{item.categories.join(', ') || '—'}</td><td>{item.active ? 'Ativo' : 'Inativo'}</td><td><button className={item.active ? 'danger-button' : ''} onClick={() => void setActive(item.id, item.name, !item.active)}>{item.active ? 'Desativar' : 'Reativar'}</button></td></tr>)}</tbody></table></section></> }
