import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api } from '../services/api'
import type { Professional, User } from '../types'
import '../patients.css'

export function UsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [professionals, setProfessionals] = useState<Professional[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const names = useMemo(() => new Map(professionals.map((professional) => [professional.id, professional.name])), [professionals])
  const load = async () => { try { const [loadedUsers, loadedProfessionals] = await Promise.all([api<User[]>('/api/users'), api<Professional[]>('/api/professionals')]); setUsers(loadedUsers); setProfessionals(loadedProfessionals) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar usuários.') } }
  useEffect(() => { void load() }, [])
  const availableProfessionals = professionals.filter((professional) => professional.active && !users.some((user) => user.professional_id === professional.id))
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setSaving(true); setError(''); try { await api('/api/users', { method: 'POST', body: JSON.stringify({ professional_id: Number(form.get('professional_id')), email: form.get('email'), password: form.get('password') }) }); formElement.reset(); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível criar o acesso.') } finally { setSaving(false) } }
  const setActive = async (id: number, active: boolean) => { const action = active ? 'reativar' : 'desativar'; if (!window.confirm(`Deseja ${action} este acesso?`)) return; try { await api(`/api/users/${id}/active?active=${active}`, { method: 'PATCH' }); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível atualizar o acesso.') } }
  return <><header className="page-heading"><div><h1>Usuários e acessos</h1><p>Controle quem pode entrar no sistema.</p></div></header><details className="registration"><summary>Criar acesso para profissional</summary><form className="professional-form" onSubmit={submit}><select name="professional_id" defaultValue="" required><option value="" disabled>Profissional</option>{availableProfessionals.map((professional) => <option value={professional.id} key={professional.id}>{professional.name}</option>)}</select><input name="email" type="email" placeholder="E-mail de login" required /><input name="password" type="password" placeholder="Senha inicial (mínimo 12 caracteres)" minLength={12} required /><button disabled={saving}>{saving ? 'Criando…' : 'Criar acesso'}</button></form></details>{error && <p className="error">{error}</p>}<section className="table-wrap"><table><thead><tr><th>Profissional</th><th>E-mail</th><th>Papel</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td>{item.professional_id ? names.get(item.professional_id) ?? `Profissional #${item.professional_id}` : 'Administrador'}</td><td>{item.email}</td><td>{item.role === 'ADMIN' ? 'Administrador' : 'Profissional'}</td><td>{item.active ? 'Ativo' : 'Inativo'}</td><td>{item.role !== 'ADMIN' && <button className={item.active ? 'danger-button' : ''} onClick={() => void setActive(item.id, !item.active)}>{item.active ? 'Desativar' : 'Reativar'}</button>}</td></tr>)}</tbody></table></section></> }
